### ISSUE TITLE
Mica studies

### ISSUE THREAD

**Issue by asarr2** [obiba/micar#2]
When i execute any query using mica.studies in mica-maelstrom by using the mica.studies function, i have this error message:
Error in content[[i]] : subscript out of bounds

reach_studies <- mica.studies(mica_connect)

I have the same error message for all the functions related to studies. 
This error didn't occur with the previous version (1.1.0).

**Comment by ymarcon** [comment]
I can reproduce it, something in the study model is breaking the JSON parser.

**Comment by asarr2** [comment]
I think it is related to the .flatten function.

Le mar. 9 avr. 2019 à 17:29, Yannick Marcon <notifications@github.com> a
écrit :

**Comment by ymarcon** [comment]
Please try with this:

```
devtools::install_github("obiba/micar", ref="micar-1.1.x")
```

**Comment by asarr2** [comment]
Thank you.

It works with :   devtools::install_github("obiba/micar", ref="micar-1.1.x")

Le mer. 10 avr. 2019 à 10:51, Yannick Marcon <notifications@github.com> a
écrit :

**Comment by ymarcon** [comment]
Release 1.1.1 is available in the CRAN.
